# -*- coding: utf-8 -*-
"""brian_tumor_predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rY-n72e0JPzpYkaS3gZVTDc3DW4MFGRa
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/dataset(brain_tumor)"
print(os.listdir(base_path))

from tensorflow.keras.models import load_model

model = load_model("/content/drive/MyDrive/brain_tumor_final_model.h5")
print("Model loaded!")

import numpy as np
import cv2
import matplotlib.pyplot as plt

# Class names (must match training order)
class_names = ['glioma', 'meningioma', 'notumor', 'pituitary']

def predict_image(model, img_path, threshold=0.8):

    # Load image
    img = cv2.imread(img_path)
    if img is None:
        raise ValueError("Image not found! Check the path.")

    # Convert BGR to RGB
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Resize to 224x224
    img_resized = cv2.resize(img, (224, 224))

    # Normalize
    img_normalized = img_resized / 255.0

    # Add batch dimension
    img_input = np.expand_dims(img_normalized, axis=0)

    # Predict
    pred_probs = model.predict(img_input)[0]
    pred_index = np.argmax(pred_probs)
    pred_class = class_names[pred_index]
    confidence = pred_probs[pred_index]

    # Show image
    plt.imshow(img)
    plt.axis("off")
    plt.title(f"Prediction: {pred_class} | Confidence: {confidence*100:.2f}%")
    plt.show()

    # Print probabilities
    print("Class probabilities:")
    for cls, prob in zip(class_names, pred_probs):
        print(f"{cls}: {prob*100:.2f}%")

    # Confidence check
    if confidence < threshold:
        print("⚠️ Model is not confident. This case should be reviewed.")
    else:
        print(f"✅ Final Prediction: {pred_class} ({confidence*100:.2f}%)")

    return pred_class, confidence


#RUN PREDICTION HERE
image_path = "/content/Te-pi_7.jpg"
predict_image(model, image_path)